#!/bin/sh
#
# Exports
dir=$ANDROID_BUILD_TOP
out=$dir/out/target/product
. $dir/vendor/xosp/tools/colors

export Changelog=Weekly-Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

if [ "$GENERATE_CHANGELOG" = "0" ]; then
	echo "Skipping Weekly ChangeLOG for Unofficial devices"
else
for i in $(seq 10);
do
export After_Date=`date --date="$i days ago" +%m-%d-%Y`
k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%m-%d-%Y`
	
	echo '' >> $Changelog;
	echo ' Copyright (C) 2013-2017 Xperia Open Source Project' >> $Changelog;
	echo '' >> $Changelog;
	echo ' Xperia Open Source Project is a project licensed under Apache License 2.0' >> $Changelog;
	echo '' >> $Changelog;
	echo ' Notice' >> $Changelog;
	echo ' This is an auto generated changelog for the XOSPChangeLOGApp.'>> $Changelog;
	echo ' The changelog is done only for official supported devices and it is updated each week.'>> $Changelog;
	echo ' If you want to see the changelog of a specific weekly build,'>> $Changelog;
	echo ' check this repository: https://github.com/XOSP-Project/utilities-xosp-changelogs' >> $Changelog;
	echo ' Find your device and check the history of the commits' >> $Changelog;
	echo '' >> $Changelog;
	echo '' >> $Changelog;
	
	# Line with after --- until was too long for a small ListView
	echo '====================' >> $Changelog;
	echo  "     "$Until_Date       >> $Changelog;
	echo '===================='	>> $Changelog;
	echo >> $Changelog;

	# Cycle through every repo to find commits between 2 dates
	repo forall -pc 'git log --oneline --after=$After_Date --until=$Until_Date' >> $Changelog
	echo >> $Changelog;
done

sed -i 's/project/   */g' $Changelog
fi

if [ -e $out/*/system/etc/$Changelog ]
then
rm $out/*/system/etc/$Changelog
fi

cp $Changelog $OUT/system/etc/
rm $Changelog

exit 0
